CREATE TABLE `delivery_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`riderId` int NOT NULL,
	`storeId` int NOT NULL,
	`status` enum('assigned','pickup_confirmed','out_for_delivery','delivered','failed_attempt','returned','cancelled') NOT NULL DEFAULT 'assigned',
	`assignedAt` timestamp NOT NULL DEFAULT (now()),
	`pickupConfirmedAt` timestamp,
	`outForDeliveryAt` timestamp,
	`deliveredAt` timestamp,
	`failedAt` timestamp,
	`returnedAt` timestamp,
	`podType` enum('otp','signature','photo','none') DEFAULT 'otp',
	`podOtp` varchar(10),
	`podOtpVerifiedAt` timestamp,
	`podPhotoUrl` text,
	`podPhotoKey` varchar(500),
	`podNote` text,
	`failedReason` enum('customer_unavailable','wrong_address','customer_refused','payment_issue','damaged_package','other'),
	`failedNote` text,
	`failedLat` decimal(10,8),
	`failedLng` decimal(11,8),
	`attemptCount` int NOT NULL DEFAULT 1,
	`isCod` boolean NOT NULL DEFAULT false,
	`codAmount` decimal(10,2),
	`codCollectedAt` timestamp,
	`codCollectedAmount` decimal(10,2),
	`codReconciled` boolean NOT NULL DEFAULT false,
	`codReconciledAt` timestamp,
	`codReconciledBy` int,
	`deliveryLat` decimal(10,8),
	`deliveryLng` decimal(11,8),
	`slaBreached` boolean NOT NULL DEFAULT false,
	`slaBreachReason` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `delivery_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `order_timestamps` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`event` enum('order_placed','prescription_uploaded','pharmacist_approved','allocation_completed','reservation_confirmed','picking_started','packed','rider_assigned','pickup_confirmed','out_for_delivery','delivered','failed_attempt','returned','cancelled','sla_breached','clarification_requested','rejected') NOT NULL,
	`occurredAt` timestamp NOT NULL DEFAULT (now()),
	`actorId` int,
	`actorType` enum('customer','pharmacist','rider','system','admin') NOT NULL DEFAULT 'system',
	`note` varchar(500),
	`breachReason` varchar(500),
	`minutesLate` int,
	CONSTRAINT `order_timestamps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rider_locations` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`riderId` int NOT NULL,
	`lat` decimal(10,8) NOT NULL,
	`lng` decimal(11,8) NOT NULL,
	`accuracy` decimal(8,2),
	`source` enum('gps','manual','network') NOT NULL DEFAULT 'gps',
	`activeTaskId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rider_locations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `routing_decisions` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`orderId` int,
	`buildingId` int,
	`requestedSkuIds` text,
	`resolvedStoreId` int,
	`resolutionPath` enum('primary_assignment','geo_nearest','geo_nearest_with_stock','pincode_fallback','manual_override','no_store_found') NOT NULL,
	`stepResults` text,
	`primaryStoreId` int,
	`primaryStoreRejectedReason` varchar(500),
	`secondaryStoreId` int,
	`secondaryStoreRejectedReason` varchar(500),
	`pincodeUsed` varchar(10),
	`etaMins` int,
	`etaSource` enum('google_maps','sla_fallback','manual') DEFAULT 'sla_fallback',
	`requiresColdChain` boolean NOT NULL DEFAULT false,
	`requiresControlledDrug` boolean NOT NULL DEFAULT false,
	`triggeredBy` enum('checkout','whatsapp','admin_override','reallocation','system') NOT NULL DEFAULT 'checkout',
	`triggeredByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `routing_decisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `store_capabilities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`licenceNumber` varchar(100),
	`licenceExpiryDate` timestamp,
	`licenceActive` boolean NOT NULL DEFAULT true,
	`serviceActive` boolean NOT NULL DEFAULT true,
	`serviceInactiveReason` varchar(300),
	`pharmacistCoverage` boolean NOT NULL DEFAULT true,
	`pharmacistName` varchar(200),
	`pharmacistRegNumber` varchar(100),
	`coldChainCapable` boolean NOT NULL DEFAULT false,
	`controlledDrugCapable` boolean NOT NULL DEFAULT false,
	`maxRiderCapacity` int NOT NULL DEFAULT 5,
	`currentRiderCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `store_capabilities_id` PRIMARY KEY(`id`),
	CONSTRAINT `store_capabilities_storeId_unique` UNIQUE(`storeId`)
);
