CREATE TABLE `discount_codes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `code` varchar(80) NOT NULL,
  `discountType` enum('percentage','fixed') NOT NULL,
  `value` decimal(10,2) NOT NULL,
  `maxDiscountAmount` decimal(10,2),
  `minOrderAmount` decimal(10,2) DEFAULT '0.00',
  `appliesTo` enum('all','store','building','customer','category','product') NOT NULL DEFAULT 'all',
  `appliesToId` varchar(80),
  `startsAt` timestamp NOT NULL,
  `endsAt` timestamp NOT NULL,
  `usageLimit` int,
  `perCustomerLimit` int,
  `usedCount` int NOT NULL DEFAULT 0,
  `isActive` boolean NOT NULL DEFAULT true,
  `requiresApprovalBelowMargin` boolean NOT NULL DEFAULT true,
  `createdBy` int,
  `approvedBy` int,
  `metadata` json,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `discount_codes_id` PRIMARY KEY(`id`),
  CONSTRAINT `discount_codes_code_unique` UNIQUE(`code`)
);
