CREATE TABLE IF NOT EXISTS `credit_notes` (
  `id` varchar(36) NOT NULL,
  `credit_note_no` varchar(64) NOT NULL,
  `original_invoice_no` varchar(100) NOT NULL,
  `bill_no` varchar(100),
  `sale_id` varchar(36),
  `order_id` int,
  `sale_return_id` varchar(36),
  `refund_id` varchar(100),
  `store_id` varchar(36) NOT NULL,
  `customer_id` varchar(36),
  `amount_paise` int NOT NULL,
  `taxable_amount_paise` int NOT NULL DEFAULT 0,
  `gst_amount_paise` int NOT NULL DEFAULT 0,
  `reason` text NOT NULL,
  `status` enum('draft','issued','cancelled','failed') NOT NULL DEFAULT 'draft',
  `issued_by` varchar(36),
  `issued_at` bigint,
  `line_splits_json` text,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `credit_notes_credit_note_no_unique` (`credit_note_no`),
  KEY `credit_notes_sale_id_idx` (`sale_id`),
  KEY `credit_notes_order_id_idx` (`order_id`),
  KEY `credit_notes_sale_return_id_idx` (`sale_return_id`),
  KEY `credit_notes_refund_id_idx` (`refund_id`),
  KEY `credit_notes_original_invoice_no_idx` (`original_invoice_no`),
  KEY `credit_notes_store_status_idx` (`store_id`, `status`)
);
