CREATE TABLE `commercial_events` (
  `event_id` varchar(64) NOT NULL,
  `aggregate_type` varchar(50) NOT NULL,
  `aggregate_id` varchar(100) NOT NULL,
  `event_type` varchar(80) NOT NULL,
  `event_version` int NOT NULL DEFAULT 1,
  `actor_type` varchar(40) NOT NULL DEFAULT 'system',
  `actor_id` varchar(100),
  `store_id` varchar(100),
  `order_id` varchar(100),
  `sale_id` varchar(100),
  `invoice_id` varchar(100),
  `reservation_id` varchar(100),
  `payment_id` varchar(100),
  `refund_id` varchar(100),
  `event_payload` json NOT NULL,
  `occurred_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idempotency_key` varchar(191),
  `correlation_id` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uq_commercial_events_idempotency` (`idempotency_key`),
  KEY `idx_commercial_events_aggregate` (`aggregate_type`, `aggregate_id`),
  KEY `idx_commercial_events_occurred` (`occurred_at`),
  KEY `idx_commercial_events_correlation` (`correlation_id`),
  KEY `idx_commercial_events_order` (`order_id`, `occurred_at`),
  KEY `idx_commercial_events_payment` (`payment_id`, `occurred_at`),
  KEY `idx_commercial_events_invoice` (`invoice_id`, `occurred_at`)
);
