CREATE TABLE IF NOT EXISTS `commercial_events` (
  `eventId` varchar(36) NOT NULL,
  `aggregateType` varchar(64) NOT NULL,
  `aggregateId` varchar(100) NOT NULL,
  `eventType` varchar(100) NOT NULL,
  `eventVersion` int NOT NULL DEFAULT 1,
  `actorType` varchar(50) NOT NULL DEFAULT 'system',
  `actorId` varchar(100),
  `storeId` varchar(100),
  `orderId` varchar(100),
  `saleId` varchar(100),
  `invoiceId` varchar(100),
  `reservationId` varchar(100),
  `paymentId` varchar(100),
  `refundId` varchar(100),
  `eventPayload` text NOT NULL,
  `occurredAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idempotencyKey` varchar(200),
  `correlationId` varchar(100),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_events_eventId_pk` PRIMARY KEY (`eventId`),
  UNIQUE KEY `uq_commercial_events_idempotency_key` (`idempotencyKey`),
  KEY `idx_commercial_events_aggregate` (`aggregateType`, `aggregateId`),
  KEY `idx_commercial_events_occurred_at` (`occurredAt`),
  KEY `idx_commercial_events_correlation_id` (`correlationId`),
  KEY `idx_commercial_events_order_id` (`orderId`),
  KEY `idx_commercial_events_payment_id` (`paymentId`),
  KEY `idx_commercial_events_invoice_id` (`invoiceId`)
);
