import React, { useMemo, useState } from "react";
export type BarcodeScanState = "idle"|"scanning"|"found"|"not_found"|"ambiguous"|"incomplete_master"|"blocked_regulated"|"error";
export type BarcodeResolvedResult = { state: BarcodeScanState; message?: string; productName?: string; batchNo?: string; warnings?: string[]; };
export function BarcodeScannerInput({ onScan, onResolved, onError }: { onScan: (rawBarcode: string) => Promise<BarcodeResolvedResult | void> | BarcodeResolvedResult | void; onResolved?: (result: BarcodeResolvedResult) => void; onError?: (error: Error) => void; }) {
  const [value, setValue] = useState(""); const [lastScannedCode, setLastScannedCode] = useState(""); const [state, setState] = useState<BarcodeScanState>("idle"); const [resolved, setResolved] = useState<BarcodeResolvedResult | null>(null);
  const disabled = useMemo(() => state === "scanning", [state]);
  async function submit(raw: string) { const normalized = raw.trim(); if (!normalized) return; setState("scanning"); setLastScannedCode(normalized); try { const result = (await onScan(normalized)) ?? { state: "found" as const }; setResolved(result); setState(result.state); onResolved?.(result); } catch (e) { setState("error"); onError?.(e as Error); } }
  return <section aria-label="Barcode scanner input" className="space-y-2"><label className="text-sm font-medium" htmlFor="barcode-scanner-input">Scan or type barcode</label><div className="flex gap-2"><input id="barcode-scanner-input" autoFocus inputMode="text" value={value} disabled={disabled} onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); void submit(value); setValue(""); } }} placeholder="Scanner wedge or manual barcode" className="w-full rounded border px-3 py-2" /><button className="rounded border px-3 py-2" disabled={disabled} onClick={() => { void submit(value); setValue(""); }}>Submit</button></div><p className="text-xs">Last scan: <strong>{lastScannedCode || "-"}</strong></p><p className="text-xs">Status: <strong>{state}</strong></p>{resolved?.productName ? <p className="text-xs">Product: {resolved.productName} {resolved.batchNo ? `(Batch ${resolved.batchNo})` : ""}</p> : null}{resolved?.warnings?.length ? <ul className="list-disc pl-5 text-xs text-amber-700">{resolved.warnings.map((w) => <li key={w}>{w}</li>)}</ul> : null}</section>;
}
export default BarcodeScannerInput;
