import pino from "pino";
import { ENV } from "../_core/env";

const logger = pino({ level: process.env.LOG_LEVEL ?? "info" });

// Breach notification recipients per DPDP and CERT-In requirements.
// Operators must update these before any production breach incident.
const DEFAULT_RECIPIENTS = ["cert-in@cert-in.org.in", "pdpb@meity.gov.in"];

export interface BreachNotificationInput {
  incidentId: string;
  affectedCustomerCount: number;
  dataCategories: string[];
  detectedAt: Date;
  containedAt?: Date;
  rootCause: string;
  mitigationActions: string[];
}

export interface BreachNotificationResult {
  notificationText: string;
  recipients: string[];
  deadline: Date;
}

function formatDate(d: Date): string {
  return d
    .toISOString()
    .replace("T", " ")
    .replace(/\.\d{3}Z$/, " UTC");
}

export function generateBreachNotification(
  input: BreachNotificationInput
): BreachNotificationResult {
  const deadline = new Date(input.detectedAt.getTime() + 72 * 60 * 60 * 1000);
  const dpoEmail = ENV.dpoEmail;

  const recipients = [
    ...DEFAULT_RECIPIENTS,
    ...(process.env.BREACH_NOTIFICATION_EXTRA_RECIPIENTS ?? "")
      .split(",")
      .map(s => s.trim())
      .filter(Boolean),
    dpoEmail,
  ];

  const notificationText = buildNotificationText(input, deadline, dpoEmail);

  logger.info(
    { incidentId: input.incidentId, deadline: deadline.toISOString() },
    "breachNotificationService: notification generated"
  );

  return { notificationText, recipients, deadline };
}

function buildNotificationText(
  input: BreachNotificationInput,
  deadline: Date,
  dpoEmail: string
): string {
  const containedLine = input.containedAt
    ? `Contained At: ${formatDate(input.containedAt)}`
    : "Contained At: ONGOING — not yet contained";

  const categoriesList = input.dataCategories.map(c => `  - ${c}`).join("\n");

  const mitigationList = input.mitigationActions
    .map((a, i) => `  ${i + 1}. ${a}`)
    .join("\n");

  return `
PERSONAL DATA BREACH NOTIFICATION
Under Section 8 of the Digital Personal Data Protection Act, 2023
and CERT-In Cyber Security Directions

============================================================

FILING DEADLINE: ${formatDate(deadline)} (72 hours from detection)

INCIDENT SUMMARY
----------------
Incident ID: ${input.incidentId}
Detected At: ${formatDate(input.detectedAt)}
${containedLine}
Affected Data Principals (Estimated): ${input.affectedCustomerCount}

DATA CATEGORIES AFFECTED
------------------------
${categoriesList}

ROOT CAUSE
----------
${input.rootCause}

MITIGATION ACTIONS TAKEN
-------------------------
${mitigationList}

ORGANISATION DETAILS
--------------------
Controller Name: 24/7 Pharmacy OS
Controller Contact: ${dpoEmail}
DPO Email: ${dpoEmail}

STATUTORY OBLIGATIONS TRIGGERED
--------------------------------
- DPDP Act Section 8: Notification to Data Protection Board within 72 hours of breach knowledge.
- CERT-In Directions: Reportable cyber incident must be reported to CERT-In within 6 hours.
- Affected data principals must be notified promptly unless law enforcement requests delay.

NEXT STEPS FOR LEGAL/COMPLIANCE TEAM
--------------------------------------
1. Confirm this notification with legal counsel before filing.
2. Determine whether law enforcement notification is required.
3. Assess obligation to notify individual affected customers.
4. Preserve all incident evidence and audit logs (minimum 180 days per CERT-In).
5. File CERT-In report at https://www.cert-in.org.in if incident constitutes a reportable cyber incident.
6. File DPDP notification to Data Protection Board when constituted.

THIS DOCUMENT IS A TEMPLATE GENERATED BY AN AUTOMATED SYSTEM.
It must be reviewed and approved by a qualified legal/compliance officer before filing.
`.trim();
}
